name: Android Demos

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/android-demos.yml'
      - 'demo/android/**'
      - '!demo/android/CheetahDemo/README.md'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - '.github/workflows/android-demos.yml'
      - 'demo/android/**'
      - '!demo/android/CheetahDemo/README.md'

jobs:
  build-cheetah-demo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11, 17, 21]

    defaults:
      run:
        working-directory: demo/android/CheetahDemo

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK  ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'

    - name: Build
      run: ./gradlew assembleDebug